name: 🐛 Bug Report
description: Create a report to help us reproduce and fix bugs
title: "[Bug] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: textarea
    id: summary
    attributes:
      label: Bug Summary
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug in one or two sentences
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide information about your development environment
      value: |
        - **Device**: [e.g., iPhone 15 Pro, MacBook Pro M3]
        - **OS Version**: [e.g., iOS 17.2, macOS 14.2]
        - **App Version**: [e.g., 1.2.0 (123)]
        - **Xcode Version**: [e.g., 15.2]
        - **Swift Version**: [e.g., 5.9]
        - **Fastlane Version**: [e.g., 2.217.0]
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue
      value: |
        1. Go to '...'
        2. Tap on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical - App crashes or major functionality broken
        - High - Significant functionality impaired
        - Medium - Minor functionality affected
        - Low - Cosmetic or minor issues
      default: 1
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: Frequency
      description: How often does this issue occur?
      options:
        - Always - 100% of the time
        - Often - 75% of the time
        - Sometimes - 50% of the time
        - Rarely - 25% of the time
        - Once - Only happened once
      default: 1
    validations:
      required: true

  - type: checkboxes
    id: platforms
    attributes:
      label: Affected Platforms
      description: Which platforms are affected by this bug?
      options:
        - label: iOS
        - label: macOS
        - label: Mac Catalyst
        - label: All platforms

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: |
        If applicable, add screenshots or videos to help explain the problem.
        You can drag and drop images or paste them directly.
      placeholder: Drag and drop images here or paste from clipboard

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: |
        Please include any relevant log output, error messages, or console output.
        Wrap logs in code blocks (```).
      render: shell
      placeholder: |
        Include crash logs, console output, or error messages here

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here. This could include:
        - Related issues or PRs
        - Workarounds you've discovered
        - When the issue first appeared
        - Any recent changes that might be related
      placeholder: Any additional information that might be helpful

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing issues that describe the same problem
          required: true
        - label: I have tested this with the latest version of the app
          required: true
        - label: I have provided all the requested information above
          required: true
        - label: I am willing to help test a potential fix