name: ❓ Question / Help
description: Ask a question or request help with the project
title: "[Question] "
labels: ["question", "help-wanted"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Need help or have a question? We're here to assist! Please provide as much context as possible.

  - type: dropdown
    id: question-type
    attributes:
      label: Question Type
      description: What type of question or help do you need?
      options:
        - Development / Implementation
        - Configuration / Setup
        - Best Practices / Architecture
        - Troubleshooting / Debugging
        - Documentation / Usage
        - Build / Deployment
        - Testing
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: |
        Please describe your question or the help you need in detail.
        Be as specific as possible to help us provide better assistance.
      placeholder: What would you like to know or what help do you need?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context and Background
      description: |
        Provide context about what you're trying to achieve or the situation you're in.
        This helps us understand your question better and provide more relevant help.
      placeholder: |
        - What are you trying to accomplish?
        - What have you tried so far?
        - Any relevant background information?

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: If relevant, please provide information about your development environment
      value: |
        - **Xcode Version**: [e.g., 15.2]
        - **macOS Version**: [e.g., 14.2]
        - **Swift Version**: [e.g., 5.9]
        - **Project Type**: [iOS App / macOS App / Framework / Other]
        - **Deployment Target**: [e.g., iOS 15.0+]
      placeholder: Fill in if relevant to your question

  - type: textarea
    id: what-tried
    attributes:
      label: What Have You Tried?
      description: |
        Describe any approaches, solutions, or research you've already attempted.
        This helps us avoid suggesting things you've already tried.
      placeholder: |
        - Searched documentation for...
        - Tried implementing...
        - Looked at examples...
        - Consulted resources...

  - type: textarea
    id: expected-outcome
    attributes:
      label: Expected Outcome
      description: What result or behavior are you trying to achieve?
      placeholder: What would you like to happen or what outcome are you seeking?

  - type: textarea
    id: code-examples
    attributes:
      label: Relevant Code (if applicable)
      description: |
        If your question involves code, please share the relevant snippets.
        Use code blocks (```) to format your code properly.
      render: swift
      placeholder: |
        ```swift
        // Your code here
        ```

  - type: textarea
    id: error-messages
    attributes:
      label: Error Messages or Logs (if applicable)
      description: |
        If you're experiencing errors, please include the full error messages or relevant log output.
        Use code blocks (```) to format logs.
      render: shell
      placeholder: |
        Include any error messages, warnings, or log output here

  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: How urgent is this question for your work?
      options:
        - Blocking - Cannot proceed without answer
        - High - Needed soon for current work
        - Medium - Helpful for planning ahead
        - Low - General curiosity or future reference
      default: 1

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: |
        Any other information that might be relevant to your question.
        Links to related documentation, tutorials, or resources you've found are also helpful.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions for similar questions
          required: true
        - label: I have checked the project documentation and README
          required: true
        - label: I have provided sufficient context and details about my question
          required: true
        - label: I am willing to provide additional information if requested