name: 🔒 Security Issue
description: Report a security vulnerability (private by default)
title: "[Security] "
labels: ["security", "critical"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT**: If this is a serious security vulnerability, please consider reporting it privately first.

        You can:
        - Email: security@yourcompany.com
        - Use GitHub Security Advisories: Go to Security tab → Report a vulnerability

        For less critical security improvements or questions, you can use this template.

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of security issue is this?
      options:
        - Vulnerability - Potential security flaw
        - Security Enhancement - Improvement to existing security
        - Security Question - Question about security practices
        - Security Documentation - Documentation improvement
        - Dependency Security - Third-party dependency issue
      default: 0
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: |
        How severe is this security issue?
        Use CVSS guidelines: https://www.first.org/cvss/calculator/3.1
      options:
        - Critical (9.0-10.0) - Immediate action required
        - High (7.0-8.9) - Important to address quickly
        - Medium (4.0-6.9) - Should be addressed soon
        - Low (0.1-3.9) - Minor security improvement
        - Informational - No immediate risk
      default: 2
    validations:
      required: true

  - type: textarea
    id: vulnerability-summary
    attributes:
      label: Vulnerability Summary
      description: |
        Provide a brief, clear summary of the security issue.
        Avoid including sensitive details that could be exploited.
      placeholder: Brief description of the security issue
    validations:
      required: true

  - type: textarea
    id: affected-components
    attributes:
      label: Affected Components
      description: Which parts of the application are affected by this security issue?
      placeholder: |
        - Authentication system
        - Data storage layer
        - Network communication
        - Specific modules or features
    validations:
      required: true

  - type: checkboxes
    id: platforms
    attributes:
      label: Affected Platforms
      description: Which platforms are affected by this security issue?
      options:
        - label: iOS
        - label: macOS
        - label: Mac Catalyst
        - label: Backend/Server components
        - label: Development/Build tools
        - label: All platforms

  - type: textarea
    id: impact-assessment
    attributes:
      label: Impact Assessment
      description: |
        Describe the potential impact of this security issue:
        - What could an attacker achieve?
        - What data could be compromised?
        - What systems could be affected?
      placeholder: |
        Potential impact:
        - Data exposure risk
        - System compromise potential
        - User privacy implications
        - Business impact

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce (if safe to share)
      description: |
        Provide steps to reproduce the issue, but be careful not to include
        information that could be used maliciously by others.
        Consider providing general steps rather than specific exploits.
      placeholder: |
        General reproduction steps (avoid sensitive details):
        1. Navigate to...
        2. Perform action...
        3. Observe issue...

  - type: textarea
    id: proof-of-concept
    attributes:
      label: Proof of Concept (if applicable)
      description: |
        If you have a safe proof of concept, you can include it here.
        Be extremely careful not to include actual exploits or sensitive information.
        Consider sharing this privately instead.
      placeholder: |
        Safe proof of concept or demonstration (if applicable)

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution or Mitigation
      description: |
        If you have ideas for how to fix this issue or mitigate the risk,
        please share them here.
      placeholder: |
        Suggested fixes or mitigations:
        - Implement proper input validation
        - Add authentication checks
        - Update dependencies
        - Apply security headers

  - type: dropdown
    id: discovery-method
    attributes:
      label: How was this discovered?
      description: How did you discover this security issue?
      options:
        - Security testing/audit
        - Code review
        - Static analysis tools
        - Dynamic analysis/penetration testing
        - User report
        - Automated vulnerability scanning
        - Dependency scanning
        - Other
    validations:
      required: true

  - type: textarea
    id: environment-info
    attributes:
      label: Environment Information
      description: Provide relevant environment details for this security issue
      value: |
        - **App Version**: [e.g., 1.2.0]
        - **Platform/OS**: [e.g., iOS 17.2, macOS 14.2]
        - **Xcode Version**: [e.g., 15.2]
        - **Build Configuration**: [Debug/Release/Staging]
        - **Deployment Environment**: [Development/Staging/Production]

  - type: textarea
    id: related-issues
    attributes:
      label: Related Issues or References
      description: |
        Any related security advisories, CVEs, or similar issues?
        Include links to relevant documentation or resources.
      placeholder: |
        - CVE references
        - Related security advisories
        - Similar issues in other projects
        - Relevant security documentation

  - type: checkboxes
    id: disclosure-agreement
    attributes:
      label: Responsible Disclosure Agreement
      description: Please confirm your commitment to responsible disclosure
      options:
        - label: I agree to responsible disclosure practices
          required: true
        - label: I will not publicly discuss details until the issue is resolved
          required: true
        - label: I understand this issue may be made private during investigation
          required: true
        - label: I am willing to work with the team to resolve this issue

  - type: textarea
    id: contact-info
    attributes:
      label: Contact Information (Optional)
      description: |
        If you'd like to be contacted about this security issue,
        please provide your preferred contact method.
        This information will be kept confidential.
      placeholder: |
        Preferred contact method for security team:
        - Email: your-email@example.com
        - Other secure communication method

  - type: markdown
    attributes:
      value: |
        ---

        **Thank you for helping to keep our project secure!**

        Security reports are taken seriously and will be investigated promptly.
        We appreciate your responsible disclosure and will keep you updated on the resolution process.